limits = [
    "stop",
    "stop",
    "stop",
    "stop",
    "stop",
    "stop",
    "stop",
    "stop",
    "stop",
    "stop",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "UltraSlow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Slow",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Medium",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "Fast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast",
    "UltraFast"
    ]

movement = {
    "noMovement":0,
    "fwUltraSlow":1, 
    "fwSlow":2,
    "fwMedium":3,
    "fwFast":4,
    "fwUltraFast":5,
    
    "ccwfwUltraSlow":6,
    "ccwfwSlow":7,
    "ccwfwMedium":8,
    "ccwfwFast":9,
    "ccwfwUltraFast":10,

    "ccwbkUltraSlow":11,
    "ccwbkSlow":12,
    "ccwbkMedium":13,
    "ccwbkFast":14,
    "ccwbkUltraFast":15,

    "ccwUltraSlowSpin":16, 
    "ccwSlowSpin":17,
    "ccwMediumSpin":18,
    "ccwFastSpin":19,
    "ccwUltraFastSpin":20,

    "cwfwUltraSlow":21,    
    "cwfwSlow":22,
    "cwfwMedium":23,
    "cwfwFast":24,
    "cwfwUltraFast":25,

    "cwbkUltraSlow":26,    
    "cwbkSlow":27,
    "cwbkMedium":28,
    "cwbkFast":29,
    "cwbkUltraFast":30,

    "cwUltraSlowSpin":31,    
    "cwSlowSpin":32,
    "cwMediumSpin":33,
    "cwFastSpin":34,
    "cwUltraFastSpin":35,

    "bkUltraSlow":36, 
    "bkSlow":37,
    "bkMedium":38,
    "bkFast":39,
    "bkUltraFast":40
}

steering = {
    ("stop","stop",0,0):"noMovement",
    ("stop","stop",0,1):"noMovement",
    ("stop","stop",1,0):"noMovement",
    ("stop","stop",1,1):"noMovement",
    ("stop","UltraSlow",0,0):"cwUltraSlowSpin",
    ("stop","UltraSlow",0,1):"ccwUltraSlowSpin",
    ("stop","UltraSlow",1,0):"cwUltraSlowSpin",
    ("stop","UltraSlow",1,1):"ccwUltraSlowSpin",
    ("stop","Slow",0,0):"cwSlowSpin",
    ("stop","Slow",0,1):"ccwSlowSpin",
    ("stop","Slow",1,0):"cwSlowSpin",
    ("stop","Slow",1,1):"ccwSlowSpin",
    ("stop","Medium",0,0):"cwMediumSpin",
    ("stop","Medium",0,1):"ccwMediuimSpin",
    ("stop","Medium",1,0):"cwMediumSpin",
    ("stop","Medium",1,1):"ccwMediumSpin",
    ("stop","Fast",0,0):"cwFastSpin",
    ("stop","Fast",0,1):"ccwFastSpin",
    ("stop","Fast",1,0):"cwFastSpin",
    ("stop","Fast",1,1):"ccwFastSpin",
    ("stop","UltraFast",0,0):"cwUltraFastSpin",
    ("stop","UltraFast",0,1):"ccwUltraFastSpin",
    ("stop","UltraFast",1,0):"cwUltraFastSpin",
    ("stop","UltraFast",1,1):"ccwUltraFastSpin",

    ("UltraSlow","stop",0,0):"fwUltraSlow",
    ("UltraSlow","stop",0,1):"fwUltraSlow",
    ("UltraSlow","stop",1,0):"bkUltraSlow",
    ("UltraSlow","stop",1,1):"bkUltraSlow",
    ("Slow","stop",0,0):"fwSlow",
    ("Slow","stop",0,1):"fwSlow",
    ("Slow","stop",1,0):"bkSlow",
    ("Slow","stop",1,1):"bkSlow",
    ("Medium","stop",0,0):"fwMedium",
    ("Medium","stop",0,1):"fwMedium",
    ("Medium","stop",1,0):"bkMedium",
    ("Medium","stop",1,1):"bkMedium",
    ("Fast","stop",0,0):"fwFast",
    ("Fast","stop",0,1):"fwFast",
    ("Fast","stop",1,0):"bkFast",
    ("Fast","stop",1,1):"bkFast",
    ("UltraFast","stop",0,0):"fwUltraFast",
    ("UltraFast","stop",0,1):"fwUltraFast",
    ("UltraFast","stop",1,0):"bkUltraFast",
    ("UltraFast","stop",1,1):"bkUltraFast",

    ("UltraSlow","UltraSlow",0,0):"cwfwUltraSlow",
    ("UltraSlow","UltraSlow",0,1):"ccwfwUltraSlow",
    ("UltraSlow","UltraSlow",1,0):"cwbkUltraSlow",
    ("UltraSlow","UltraSlow",1,1):"ccwbkUltraSlow",

    ("UltraSlow","Slow",0,0):"cwfwSlow",
    ("UltraSlow","Slow",0,1):"ccwfwSlow",
    ("UltraSlow","Slow",1,0):"cwbkSlow",
    ("UltraSlow","Slow",1,1):"ccwbkSlow",

    ("UltraSlow","Medium",0,0):"cwfwMedium",
    ("UltraSlow","Medium",0,1):"ccwfwMedium",
    ("UltraSlow","Medium",1,0):"cwbkMedium",
    ("UltraSlow","Medium",1,1):"ccwbkMedium",

    ("UltraSlow","Fast",0,0):"cwfwFast",
    ("UltraSlow","Fast",0,1):"ccwfwFast",
    ("UltraSlow","Fast",1,0):"cwbkFast",
    ("UltraSlow","Fast",1,1):"ccwbkFast",

    ("UltraSlow","UltraFast",0,0):"cwfwUltraFast",
    ("UltraSlow","UltraFast",0,1):"ccwfwUltraFast",
    ("UltraSlow","UltraFast",1,0):"cwbkUltraFast",
    ("UltraSlow","UltraFast",1,1):"ccwbkUltraFast",

    ("Slow","UltraSlow",0,0):"cwfwUltraSlow",
    ("Slow","UltraSlow",0,1):"ccwfwUltraSlow",
    ("Slow","UltraSlow",1,0):"cwbkUltraSlow",
    ("Slow","UltraSlow",1,1):"ccwbkUltraSlow",

    ("Slow","Slow",0,0):"cwfwSlow",
    ("Slow","Slow",0,1):"ccwfwSlow",
    ("Slow","Slow",1,0):"cwbkSlow",
    ("Slow","Slow",1,1):"ccwbkSlow",

    ("Slow","Medium",0,0):"cwfwMedium",
    ("Slow","Medium",0,1):"ccwfwMedium",
    ("Slow","Medium",1,0):"cwbkMedium",
    ("Slow","Medium",1,1):"ccwbkMedium",

    ("Slow","Fast",0,0):"cwfwFast",
    ("Slow","Fast",0,1):"ccwfwFast",
    ("Slow","Fast",1,0):"cwbkFast",
    ("Slow","Fast",1,1):"ccwbkFast",

    ("Slow","UltraFast",0,0):"cwfwUltraFast",
    ("Slow","UltraFast",0,1):"ccwfwUltraFast",
    ("Slow","UltraFast",1,0):"cwbkUltraFast",
    ("Slow","UltraFast",1,1):"ccwbkUltraFast",

    ("Medium","UltraSlow",0,0):"cwfwUltraSlow",
    ("Medium","UltraSlow",0,1):"ccwfwUltraSlow",
    ("Medium","UltraSlow",1,0):"cwbkUltraSlow",
    ("Medium","UltraSlow",1,1):"ccwbkUltraSlow",

    ("Medium","Slow",0,0):"cwfwSlow",
    ("Medium","Slow",0,1):"ccwfwSlow",
    ("Medium","Slow",1,0):"cwbkSlow",
    ("Medium","Slow",1,1):"ccwbkSlow",

    ("Medium","Medium",0,0):"cwfwMedium",
    ("Medium","Medium",0,1):"ccwfwMedium",
    ("Medium","Medium",1,0):"cwbkMedium",
    ("Medium","Medium",1,1):"ccwbkMedium",

    ("Medium","Fast",0,0):"cwfwFast",
    ("Medium","Fast",0,1):"ccwfwFast",
    ("Medium","Fast",1,0):"cwbkFast",
    ("Medium","Fast",1,1):"ccwbkFast",

    ("Medium","UltraFast",0,0):"cwfwUltraFast",
    ("Medium","UltraFast",0,1):"ccwfwUltraFast",
    ("Medium","UltraFast",1,0):"cwbkUltraFast",
    ("Medium","UltraFast",1,1):"ccwbkUltraFast",

    ("Fast","UltraSlow",0,0):"cwfwUltraSlow",
    ("Fast","UltraSlow",0,1):"ccwfwUltraSlow",
    ("Fast","UltraSlow",1,0):"cwbkUltraSlow",
    ("Fast","UltraSlow",1,1):"ccwbkUltraSlow",

    ("Fast","Slow",0,0):"cwfwSlow",
    ("Fast","Slow",0,1):"ccwfwSlow",
    ("Fast","Slow",1,0):"cwbkSlow",
    ("Fast","Slow",1,1):"ccwbkSlow",

    ("Fast","Medium",0,0):"cwfwMedium",
    ("Fast","Medium",0,1):"ccwfwMedium",
    ("Fast","Medium",1,0):"cwbkMedium",
    ("Fast","Medium",1,1):"ccwbkMedium",

    ("Fast","Fast",0,0):"cwfwFast",
    ("Fast","Fast",0,1):"ccwfwFast",
    ("Fast","Fast",1,0):"cwbkFast",
    ("Fast","Fast",1,1):"ccwbkFast",

    ("Fast","UltraFast",0,0):"cwfwUltraFast",
    ("Fast","UltraFast",0,1):"ccwfwUltraFast",
    ("Fast","UltraFast",1,0):"cwbkUltraFast",
    ("Fast","UltraFast",1,1):"ccwbkUltraFast",

    ("Medium","UltraSlow",0,0):"cwfwUltraSlow",
    ("Medium","UltraSlow",0,1):"ccwfwUltraSlow",
    ("Medium","UltraSlow",1,0):"cwbkUltraSlow",
    ("Medium","UltraSlow",1,1):"ccwbkUltraSlow",

    ("UltraFast","Slow",0,0):"cwfwSlow",
    ("UltraFast","Slow",0,1):"ccwfwSlow",
    ("UltraFast","Slow",1,0):"cwbkSlow",
    ("UltraFast","Slow",1,1):"ccwbkSlow",

    ("UltraFast","Medium",0,0):"cwfwMedium",
    ("UltraFast","Medium",0,1):"ccwfwMedium",
    ("UltraFast","Medium",1,0):"cwbkMedium",
    ("UltraFast","Medium",1,1):"ccwbkMedium",

    ("UltraFast","Fast",0,0):"cwfwFast",
    ("UltraFast","Fast",0,1):"ccwfwFast",
    ("UltraFast","Fast",1,0):"cwbkFast",
    ("UltraFast","Fast",1,1):"ccwbkFast",

    ("UltraFast","UltraFast",0,0):"cwfwUltraFast",
    ("UltraFast","UltraFast",0,1):"ccwfwUltraFast",
    ("UltraFast","UltraFast",1,0):"cwbkUltraFast",
    ("UltraFast","UltraFast",1,1):"ccwbkUltraFast",
}   