#pragma once


#define MOTOR_LEFT_STEP 0
#define MOTOR_RIGHT_STEP 1
#define MOTOR_LEFT_EN 2
#define MOTOR_RIGHT_EN 3
#define MOTOR_LEFT_DIR 4
#define MOTOR_RIGHT_DIR 5



#define ROTATION_SPEED_HIGH {44,34,24,18,10,0}
#define ROTATION_SPEED_LOW {22,17,12,9,5,0}
